version: '3.4'

services:
  tiendaservicios.api.autor:
    image: tiendaserviciosapiautor:dev
    container_name: TiendaServicios.Api.Autor
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Autor"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios\TiendaServicios.Api.Autor:/app
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios:/src
      - C:\Users\mmois\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\mmois\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Autor.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  tiendaservicios.api.carritocompra:
    image: tiendaserviciosapicarritocompra:dev
    container_name: TiendaServicios.Api.CarritoCompra
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.CarritoCompra"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios\TiendaServicios.Api.CarritoCompra:/app
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios:/src
      - C:\Users\mmois\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\mmois\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.CarritoCompra.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  tiendaservicios.api.libreria:
    image: tiendaserviciosapilibreria:dev
    container_name: TiendaServicios.Api.Libreria
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Libreria"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios\TiendaServicios.Api.Libreria:/app
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios:/src
      - C:\Users\mmois\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\mmois\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Libreria.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  tiendaservicios.api.login:
    image: tiendaserviciosapilogin:dev
    container_name: TiendaServicios.Api.Login
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Login"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios\TiendaServicios.Api.Login:/app
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios:/src
      - C:\Users\mmois\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\mmois\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Login.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  tiendaservicios.api.seguridad:
    image: tiendaserviciosapiseguridad:dev
    container_name: TiendaServicios.Api.Seguridad
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TiendaServicios.Api.Seguridad"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios\TiendaServicios.Api.Seguridad:/app
      - C:\Users\mmois\source\repos\BookStore\TiendaServicios:/src
      - C:\Users\mmois\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\mmois\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/TiendaServicios.Api.Seguridad.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
